import { AgeCalculatorTool } from "@/components/tools/AgeCalculatorTool";
import { WordCounterTool } from "@/components/tools/WordCounterTool";
import { CaseConverterTool } from "@/components/tools/CaseConverterTool";
import { LoremIpsumTool } from "@/components/tools/LoremIpsumTool";
import { JsonFormatterTool } from "@/components/tools/JsonFormatterTool";
import { Base64Tool } from "@/components/tools/Base64Tool";
import { UrlEncoderTool } from "@/components/tools/UrlEncoderTool";
import { PasswordGeneratorTool } from "@/components/tools/PasswordGeneratorTool";
import { HashGeneratorTool } from "@/components/tools/HashGeneratorTool";
import { UuidGeneratorTool } from "@/components/tools/UuidGeneratorTool";
import { ColorConverterTool } from "@/components/tools/ColorConverterTool";
import {
  ArmyBodyFatCalculatorTool,
  BmiCalculatorTool,
  BmrCalculatorTool,
  BodyFatCalculatorTool,
  CalorieCalculatorTool,
  CaloriesBurnedCalculatorTool,
  HealthyWeightCalculatorTool,
  IdealWeightCalculatorTool,
  LeanBodyMassCalculatorTool,
  OneRepMaxCalculatorTool,
  PaceCalculatorTool,
  TargetHeartRateCalculatorTool,
  TdeeCalculatorTool,
} from "@/components/tools/health/FitnessTools";
import {
  ConceptionCalculatorTool,
  DueDateCalculatorTool,
  OvulationCalculatorTool,
  PeriodCalculatorTool,
  PregnancyCalculatorTool,
  PregnancyConceptionCalculatorTool,
  PregnancyWeightGainCalculatorTool,
} from "@/components/tools/health/PregnancyTools";
import {
  BacCalculatorTool,
  BodySurfaceAreaCalculatorTool,
  BodyTypeCalculatorTool,
  CarbohydrateCalculatorTool,
  FatIntakeCalculatorTool,
  GfrCalculatorTool,
  MacroCalculatorTool,
  ProteinCalculatorTool,
} from "@/components/tools/health/NutritionTools";
import {
  AmortizationCalculatorTool,
  AprCalculatorTool,
  AutoLeaseCalculatorTool,
  AutoLoanCalculatorTool,
  BoatLoanCalculatorTool,
  BusinessLoanCalculatorTool,
  CashBackOrLowInterestCalculatorTool,
  CreditCardCalculatorTool,
  CreditCardsPayoffCalculatorTool,
  DebtConsolidationCalculatorTool,
  DebtPayoffCalculatorTool,
  DebtToIncomeCalculatorTool,
  DownPaymentCalculatorTool,
  FhaLoanCalculatorTool,
  HelocCalculatorTool,
  HomeEquityLoanCalculatorTool,
  HouseAffordabilityCalculatorTool,
  LeaseCalculatorTool,
  LoanCalculatorTool,
  MortgageCalculatorTool,
  MortgagePayoffCalculatorTool,
  PaymentCalculatorTool,
  PersonalLoanCalculatorTool,
  RealEstateCalculatorTool,
  RefinanceCalculatorTool,
  RentalPropertyCalculatorTool,
  RentCalculatorTool,
  RentVsBuyCalculatorTool,
  RepaymentCalculatorTool,
  StudentLoanCalculatorTool,
  VaMortgageCalculatorTool,
} from "@/components/tools/finance/LoanTools";
import {
  AnnuityCalculatorTool,
  AnnuityPayoutCalculatorTool,
  AverageReturnCalculatorTool,
  BondCalculatorTool,
  CdCalculatorTool,
  CompoundInterestCalculatorTool,
  FinanceCalculatorTool,
  FutureValueCalculatorTool,
  InflationCalculatorTool,
  InterestCalculatorTool,
  InterestRateCalculatorTool,
  InvestmentCalculatorTool,
  IrrCalculatorTool,
  MutualFundCalculatorTool,
  PaybackPeriodCalculatorTool,
  PresentValueCalculatorTool,
  RoiCalculatorTool,
  SavingsCalculatorTool,
  SimpleInterestCalculatorTool,
} from "@/components/tools/finance/InvestTools";
import {
  BudgetCalculatorTool,
  CollegeCostCalculatorTool,
  CommissionCalculatorTool,
  CurrencyCalculatorTool,
  DepreciationCalculatorTool,
  DiscountCalculatorTool,
  EstateTaxCalculatorTool,
  FourOhOneKCalculatorTool,
  IncomeTaxCalculatorTool,
  IraCalculatorTool,
  MarginCalculatorTool,
  MarriageTaxCalculatorTool,
  PensionCalculatorTool,
  RetirementCalculatorTool,
  RmdCalculatorTool,
  RothIraCalculatorTool,
  SalaryCalculatorTool,
  SalesTaxCalculatorTool,
  SocialSecurityCalculatorTool,
  TakeHomePaycheckCalculatorTool,
  VatCalculatorTool,
} from "@/components/tools/finance/RetirementTaxTools";

const toolComponents = {
  "age-calculator": AgeCalculatorTool,
  "bmi-calculator": BmiCalculatorTool,
  "calorie-calculator": CalorieCalculatorTool,
  "body-fat-calculator": BodyFatCalculatorTool,
  "bmr-calculator": BmrCalculatorTool,
  "ideal-weight-calculator": IdealWeightCalculatorTool,
  "pace-calculator": PaceCalculatorTool,
  "army-body-fat-calculator": ArmyBodyFatCalculatorTool,
  "lean-body-mass-calculator": LeanBodyMassCalculatorTool,
  "healthy-weight-calculator": HealthyWeightCalculatorTool,
  "calories-burned-calculator": CaloriesBurnedCalculatorTool,
  "one-rep-max-calculator": OneRepMaxCalculatorTool,
  "target-heart-rate-calculator": TargetHeartRateCalculatorTool,
  "pregnancy-calculator": PregnancyCalculatorTool,
  "pregnancy-weight-gain-calculator": PregnancyWeightGainCalculatorTool,
  "pregnancy-conception-calculator": PregnancyConceptionCalculatorTool,
  "due-date-calculator": DueDateCalculatorTool,
  "ovulation-calculator": OvulationCalculatorTool,
  "conception-calculator": ConceptionCalculatorTool,
  "period-calculator": PeriodCalculatorTool,
  "macro-calculator": MacroCalculatorTool,
  "carbohydrate-calculator": CarbohydrateCalculatorTool,
  "protein-calculator": ProteinCalculatorTool,
  "fat-intake-calculator": FatIntakeCalculatorTool,
  "tdee-calculator": TdeeCalculatorTool,
  "gfr-calculator": GfrCalculatorTool,
  "body-type-calculator": BodyTypeCalculatorTool,
  "body-surface-area-calculator": BodySurfaceAreaCalculatorTool,
  "bac-calculator": BacCalculatorTool,
  "word-counter": WordCounterTool,
  "case-converter": CaseConverterTool,
  "lorem-ipsum-generator": LoremIpsumTool,
  "json-formatter": JsonFormatterTool,
  "base64-encoder": Base64Tool,
  "url-encoder": UrlEncoderTool,
  "password-generator": PasswordGeneratorTool,
  "hash-generator": HashGeneratorTool,
  "uuid-generator": UuidGeneratorTool,
  "color-converter": ColorConverterTool,
  "mortgage-calculator": MortgageCalculatorTool,
  "amortization-calculator": AmortizationCalculatorTool,
  "mortgage-payoff-calculator": MortgagePayoffCalculatorTool,
  "house-affordability-calculator": HouseAffordabilityCalculatorTool,
  "rent-calculator": RentCalculatorTool,
  "debt-to-income-ratio-calculator": DebtToIncomeCalculatorTool,
  "real-estate-calculator": RealEstateCalculatorTool,
  "refinance-calculator": RefinanceCalculatorTool,
  "rental-property-calculator": RentalPropertyCalculatorTool,
  "apr-calculator": AprCalculatorTool,
  "fha-loan-calculator": FhaLoanCalculatorTool,
  "va-mortgage-calculator": VaMortgageCalculatorTool,
  "home-equity-loan-calculator": HomeEquityLoanCalculatorTool,
  "heloc-calculator": HelocCalculatorTool,
  "down-payment-calculator": DownPaymentCalculatorTool,
  "rent-vs-buy-calculator": RentVsBuyCalculatorTool,
  "auto-loan-calculator": AutoLoanCalculatorTool,
  "cash-back-or-low-interest-calculator": CashBackOrLowInterestCalculatorTool,
  "auto-lease-calculator": AutoLeaseCalculatorTool,
  "interest-calculator": InterestCalculatorTool,
  "investment-calculator": InvestmentCalculatorTool,
  "finance-calculator": FinanceCalculatorTool,
  "compound-interest-calculator": CompoundInterestCalculatorTool,
  "interest-rate-calculator": InterestRateCalculatorTool,
  "savings-calculator": SavingsCalculatorTool,
  "simple-interest-calculator": SimpleInterestCalculatorTool,
  "cd-calculator": CdCalculatorTool,
  "bond-calculator": BondCalculatorTool,
  "mutual-fund-calculator": MutualFundCalculatorTool,
  "average-return-calculator": AverageReturnCalculatorTool,
  "irr-calculator": IrrCalculatorTool,
  "roi-calculator": RoiCalculatorTool,
  "payback-period-calculator": PaybackPeriodCalculatorTool,
  "present-value-calculator": PresentValueCalculatorTool,
  "future-value-calculator": FutureValueCalculatorTool,
  "retirement-calculator": RetirementCalculatorTool,
  "401k-calculator": FourOhOneKCalculatorTool,
  "pension-calculator": PensionCalculatorTool,
  "social-security-calculator": SocialSecurityCalculatorTool,
  "annuity-calculator": AnnuityCalculatorTool,
  "annuity-payout-calculator": AnnuityPayoutCalculatorTool,
  "roth-ira-calculator": RothIraCalculatorTool,
  "ira-calculator": IraCalculatorTool,
  "rmd-calculator": RmdCalculatorTool,
  "income-tax-calculator": IncomeTaxCalculatorTool,
  "salary-calculator": SalaryCalculatorTool,
  "marriage-tax-calculator": MarriageTaxCalculatorTool,
  "estate-tax-calculator": EstateTaxCalculatorTool,
  "take-home-paycheck-calculator": TakeHomePaycheckCalculatorTool,
  "loan-calculator": LoanCalculatorTool,
  "payment-calculator": PaymentCalculatorTool,
  "currency-calculator": CurrencyCalculatorTool,
  "inflation-calculator": InflationCalculatorTool,
  "sales-tax-calculator": SalesTaxCalculatorTool,
  "credit-card-calculator": CreditCardCalculatorTool,
  "credit-cards-payoff-calculator": CreditCardsPayoffCalculatorTool,
  "debt-payoff-calculator": DebtPayoffCalculatorTool,
  "debt-consolidation-calculator": DebtConsolidationCalculatorTool,
  "repayment-calculator": RepaymentCalculatorTool,
  "student-loan-calculator": StudentLoanCalculatorTool,
  "college-cost-calculator": CollegeCostCalculatorTool,
  "vat-calculator": VatCalculatorTool,
  "depreciation-calculator": DepreciationCalculatorTool,
  "margin-calculator": MarginCalculatorTool,
  "discount-calculator": DiscountCalculatorTool,
  "business-loan-calculator": BusinessLoanCalculatorTool,
  "personal-loan-calculator": PersonalLoanCalculatorTool,
  "boat-loan-calculator": BoatLoanCalculatorTool,
  "lease-calculator": LeaseCalculatorTool,
  "budget-calculator": BudgetCalculatorTool,
  "commission-calculator": CommissionCalculatorTool,
} as const;

export type ToolSlug = keyof typeof toolComponents;

export function ToolWorkspace({ slug }: { slug: string }) {
  const Component = toolComponents[slug as ToolSlug];
  if (!Component) {
    return <p className="text-ink-muted">This tool is not available yet.</p>;
  }
  return <Component />;
}
